image: registry.gitlab.com/everythingfunctional/dockerfpm

variables:
    GIT_SUBMODULE_STRATEGY: normal

test:
  script:
    - fpm test
    - valgrind --leak-check=full --error-exitcode=1 tests_build/vegetable_driver
