stages:
  - test
  - documentation

test:
  image: registry.gitlab.com/everythingfunctional/dockerfpm
  script:
    - ./run_ci.sh

documentation:
  image: python:2.7
  script:
    - pip install ford
    - ford doc/front-matter.md
  artifacts:
    paths:
      - public
